// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Licitacoes.Core.Models
{
    public partial class LicitacoesContext : DbContext
    {
        public LicitacoesContext()
        {
        }

        public LicitacoesContext(DbContextOptions<LicitacoesContext> options)
            : base(options)
        {
            Database.EnsureCreated();
        }

        public virtual DbSet<Licitacoes> Licitacoes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
               optionsBuilder.UseSqlServer("Server=localhost,1433;Database=licitacoes;User Id=sa;Password=123456aA;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}