// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Licitacoes.Core.Models
{
    [Table("licitacoes")]
    public class Licitacoes
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        [DisplayName("Número da Licitação")]
        public string LicitacaoNumber { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        [DisplayName("Descrição")]
        public string Description { get; set; }
        [Column(TypeName = "date")]
        [DisplayName("Data de Abertura")]
        public DateTime DataOpening { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        [DisplayName("Status da Licitação")]
        public string Status { get; set; }
    }
}